### ISSUE TITLE
Timeout while waiting for response.  Method: csharp/metadata

### ISSUE THREAD

**Issue by hungyiloo** [razzmatazz/csharp-language-server#1]
First of all, thanks so much for this amazing hack! I've been using it for a few weeks now.

This timeout happens when using `lsp-ui-peek-find-definitions` to go into a metadata file but it doesn't happen on regular `lsp-find-definition`. Other than the error itself, Emacs also hangs. It seems I can mash C-g to get out of a little earlier.

I'm more than happy to blame something in my config, but I haven't been able to find a workaround so far. Do you have any clues?

**Comment by hungyiloo** [comment]
Thanks for trying to replicate @razzmatazz --- I know I didn't give you much info to go by. I appreciate it.

I'm on an Emacs 28 build with PGTK from around July. I'll try updating to latest to see if it changes anything.

I'm also running on Doom Emacs. I have come to realise that doom has some wrappers around the lsp commands, and may have other advice that I'm unaware of. I'll try debugging without it when I have the time. I'm actually very busy using your language server for work 😄 

I can consistently reproduce it with the .NET Core/.NET 5.0 projects that I usually work with. And just now I managed to get it to happen by opening metadata on `Console.Writeline` in `Program.cs` on a newly created project using `dotnet new console`. I've attached an archive of my test project, in case it helps.

[scratch.tar.gz](https://github.com/razzmatazz/csharp-language-server/files/7310657/scratch.tar.gz)

**Comment by razzmatazz** [comment]
> I can consistently reproduce it with the .NET Core/.NET 5.0 projects that I usually work with. And just now I managed to get it to happen by opening metadata on `Console.Writeline` in `Program.cs` on a newly created project using `dotnet new console`. I've attached an archive of my test project, in case it helps.

I am not sure I can reproduce this.. So what I do:
- go to definition to `System.Console` -- lsp opens me metadata file for it with cursor pointing to class name
- i go to `void WriteLine()`
- `M-x lsp-ui-peek-find-definitions`

I get a list of refs.. So not sure if I'm replicating this properly.

Could you check:
- if CPU is used by csharp-ls or emacs during the time the editor is blocked? which one is blocking?
- If `*lsp-log*` and `*Messages*` show any crash or stack trace or interesting message?

**Comment by razzmatazz** [comment]
I have also released a newer version with updated roslyn libs, so maybe *that* helps but probably not..

**Comment by hungyiloo** [comment]
I was on 0.1.3 and I could reproduce it just now. After updating to 0.1.4 it has fixed it completely in my test setup. It also works smoothly in my work projects too. Magic! Thanks so much!

To answer your questions anyway:
1. `*lsp-log*` had no errors or stack traces. It looked pretty innocuous to me
```
Command "csharp-ls" is present on the path.
Command "csharp-ls" is present on the path.
Command "csharp-ls" is present on the path.
Found the following clients for /home/hy/temp/scratch/Program.cs: (server-id csharp-ls, priority -2)
The following clients were selected based on priority: (server-id csharp-ls, priority -2)
Command "csharp-ls" is present on the path.
Command "csharp-ls" is present on the path.
Command "csharp-ls" is present on the path.
Found the following clients for /home/hy/temp/scratch/.cache/lsp-csharp/metadata/projects/scratch/assemblies/System.Console/System.Console.cs: (server-id csharp-ls, priority -2)
The following clients were selected based on priority: (server-id csharp-ls, priority -2)
```
2. `*Messages*` only showed the error in the title of this issue: `Timeout while waiting for response. Method: csharp/metadata`

Really appreciate the update and trying so hard to reproduce it.
