### ISSUE TITLE
dotnet tool install --global csharp-ls does not install to the correct directory

### ISSUE THREAD

**Issue by Rimann91** [razzmatazz/csharp-language-server#118]
attempting to follow the install instructions in the readme, copy pasting the command exactly, dotnet tells me that csharp-ls was installed successfully, but the command does not execute it. Returns 'command not found'. The tool is not in  `.dontet/tools`. Trying to innstall again returns 'csharp-ls is already installed'. 

- Environment: WSL2 Ubuntu on windows10
- Dotnet version 7.0.403

Things I have tried
- restarting ws, and windows
- uninstalling and reinstalling dotnet7 form the Microsoft PPA
- verified .dotnet/tools is in my path

I do not know where or if the package is actually downloaded to my machine. I can not find it anywhere.

**Comment by scientificworld** [comment]
On my system, it's installed in `~/.dotnet/tools`. If you cannot find it there, maybe you can try `find / -name csharp-ls`.

**Comment by razzmatazz** [comment]
Mostly likely you just need to add `~/.dotnet/tools` to your `PATH`, like posted above.
