### ISSUE TITLE
Add support for textDocument/typeDefinition

### ISSUE THREAD

**Issue by rudiejd** [razzmatazz/csharp-language-server#120]
thank you all for the awesome project! While this LSP does not provide as many suggestions as Omnisharp, it's way faster for large projects. I noticed when switching from OmniSharp to csharp-language-server that this language server does not provide support for [textDocument/typeDefinition](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_typeDefinition), which I make heavy use of for LINQ. is there any plan to implement this feature? If not, I'd love to give it a shot

**Comment by razzmatazz** [comment]
hi @rudiejd 
Thank you for your kind words :) 

I started this project to scratch my personal itch,--feel free to provide implementation for this endpoint as a PR, I don't know of anyone else who is working on this at the moment.

csharp-ls is written as a (relatively) simple mapper from lsp to roslyn apis, so I'd start looking at roslyn documentation for ideas how to adapt that api to lsp semantics

**Comment by searleser97** [comment]
do we have this already ?
