### ISSUE TITLE
Adding support for progress

### ISSUE THREAD

**Issue by rudiejd** [razzmatazz/csharp-language-server#125]
I was looking into implementing [progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress), but I haven't gotten really far. Specifically, it seems difficult to extract information from Roslyn when we're building the solution and/or the project. Any ideas here? Would we want to parse the MSBuild output from stdout?

**Comment by razzmatazz** [comment]
@tcx4c70 has added support for this in https://github.com/razzmatazz/csharp-language-server/commit/7fe7295d9b60a7062c498ba8d45da3fd15e37bae

**Comment by razzmatazz** [comment]
Closing as per my last comment
