### ISSUE TITLE
running as a local package

### ISSUE THREAD

**Issue by kstatz12** [razzmatazz/csharp-language-server#126]
I remember getting this working the last PR i did, but i forget the steps to run this locally. 

does anyone have any tips?

**Comment by BeauCranston** [comment]
Going off the dome so hopefully this is accurate. I’m on windows btw.

- Clone repo
- Globally uninstall csharp-ls from your tools
- Make whatever changes you want to local repo
- Run dotnet pack
- Run dotnet tool install csharp-ls -g —add-source .\nupkg

Now csharp-ls is using your local copy.

Edit your lsp config to include the csharp-ls server and have the cmd set to csharp-ls and configure whatever else you need. 

If you still need help after reading this ill send a picture of my lsp config
