### ISSUE TITLE
[question] can one provide an example of using the decompiler when jumping to definition using coc?

### ISSUE THREAD

**Issue by amirongit** [razzmatazz/csharp-language-server#139]
this is the configuration in coc settings which sets csharp ls up & running for cs files

```json
    "languageserver": {
        "csharp-ls": {
            "command": "csharp-ls",
            "filetypes": [
                "cs"
            ],
            "rootPatterns": [
                "*.csproj",
                ".git/",
                "*.sln"
            ],
        }
    }
```

can one provide an example of using the decompiler when the definition exists in an assembly?! (when using <Plug>(coc-definition))

**Comment by Decodetalkers** [comment]
Emm, it is for nvim lsp, so can't be used for coc, but you can try to write one, it is quite simple to imply it

**Comment by amirongit** [comment]
ok then, tanks
