### ISSUE TITLE
Code Formatting On The Roadmap

### ISSUE THREAD

**Issue by kstatz12** [razzmatazz/csharp-language-server#14]
Is code formatting on the roadmap? Its the one thing I miss from omnisharp-roslyn

**Comment by razzmatazz** [comment]
Oh definitely. Currently busy trying to fit lsp request cancellation support to fix some of the performance issues due to long running requests (code lenses).

**Comment by kstatz12** [comment]
I would be interested in helping out if you point me where you want it to happen

**Comment by razzmatazz** [comment]
Oh definitely, please

You should start looking here:
- https://microsoft.github.io/language-server-protocol/specification#textDocument_onTypeFormatting
  - there is also other types of formatting (whole document) you could take a stab at first if easier
- override `TextDocumentOnTypeFormatting`
  - see https://github.com/ionide/LanguageServerProtocol/blob/main/src/LanguageServerProtocol.fs#L2628
- expose capability by setting `DocumentOnTypeFormattingProvider`
  - see https://github.com/ionide/LanguageServerProtocol/blob/main/src/LanguageServerProtocol.fs#L1038

for implementation guidelines I would start investingating what omnisharp-roslyn does here (omnisharp-roslyn has a service-based design so you have to dig deeper):
- https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpDocumentOnTypeFormattingHandler.cs#L35
- https://github.com/OmniSharp/omnisharp-roslyn/blob/ff21ac475cdf8afb15579f2b5fb346945db2a7e9/src/OmniSharp.Roslyn.CSharp/Services/Formatting/FormatAfterKeystrokeService.cs#L40
- https://github.com/OmniSharp/omnisharp-roslyn/blob/ff21ac475cdf8afb15579f2b5fb346945db2a7e9/src/OmniSharp.Roslyn.CSharp/Workers/Formatting/FormattingWorker.cs#L23

**Comment by kstatz12** [comment]
Aye aye. I'll take a stab at it

**Comment by kstatz12** [comment]
So ive made some progress (branch for reference https://github.com/kstatz12/csharp-language-server/tree/basics)
 but im stuck on one bit that is hopefully just me being a dumbass. 

```
override __.TextDocumentFormatting(format: Types.DocumentFormattingParams) : AsyncLspResult<Types.TextEdit [] option> =
        async {
            let maybeDocument = getDocumentForUri state format.TextDocument.Uri
            let! formattingChanges = 
                match maybeDocument with
                | Some doc -> handleTextDocumentFormatAsync doc
                | _ -> async { return [] }
            return formattingChanges |> Some |> success
        }
 ```

its not happy with the empty list return here and im flummoxed as to how to get around it

**Comment by kstatz12** [comment]
im working on OnType formatting since that is a bit of a doozy. There are a lot of layers of abstraction to unwind/port over

**Comment by razzmatazz** [comment]
> its not happy with the empty list return here and im flummoxed as to how to get around it

Not 100% sure but maybe you can try return `None |> success` there? ..not sure what the LSP protocol says about failure response format here

**Comment by razzmatazz** [comment]
this is working good for me with #15 , closing
