### ISSUE TITLE
Code Action: Extract Interface (Produces Error)

### ISSUE THREAD

**Issue by JorgeHerreraU** [razzmatazz/csharp-language-server#152]
Hello
Attempting to extract interface from Foo produces "nil" value error
```
namespace Sandbox
{
    public class Foo
    {
        public string Bar(string s) => s;
    }
}
```

`
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:642: attempt to index local 'action' (a nil value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:642: in function 'apply_action'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:697: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
`

**Comment by razzmatazz** [comment]
Hey @JorgeHerreraU.
Just to confirm, are you using the latest version, 0.12.0?

**Comment by JorgeHerreraU** [comment]
Hi @razzmatazz 
There you are
```
NVIM v0.9.5
csharp_ls: v0.12.0
OS: openSUSE Tumbleweed
dotnet: v8.0.204
```

**Comment by razzmatazz** [comment]
Can confirm with emacs/eglot

**Comment by razzmatazz** [comment]
Should be fixed with this commit: https://github.com/razzmatazz/csharp-language-server/commit/f6b7138ac73c6d4e0ad84b55730ce163857b779c

**Comment by razzmatazz** [comment]
0.13.0 has been released that contains a fix for this issue:
- https://github.com/razzmatazz/csharp-language-server/releases/tag/0.13.0
