### ISSUE TITLE
Insert better namespace managing

### ISSUE THREAD

**Issue by Wordluc** [razzmatazz/csharp-language-server#159]
I would like to have an warning when a namespace isnt match the directory, or have a system to autocreate a namespace declaration based on file`s position

**Comment by razzmatazz** [comment]
Does VS provide this? I think this should be doable by adding custom roslyn analyzer instead.
Not sure if roslyn as integrated with csharp-ls supports those though..

**Comment by markchristianlacap** [comment]
You could try this simple plugin that autocompletes the namespace based on your folder structure https://github.com/markchristianlacap/csharp-namespace.nvim

**Comment by Wordluc** [comment]
i've been using this for a while now
`vim.api.nvim_create_user_command('Gnamespace', function()
	local dir = vim.fn.expand("%:.")
	local namespace = {}
	for segment in dir:gmatch("[^/|\\]+") do
		table.insert(namespace, segment)
	end
	local newPath = table.concat(namespace, ".", 1, #namespace - 1)
	vim.api.nvim_feedkeys("inamespace " .. newPath .. ";", "n", true)
end, { bang = true, nargs = '*' })
`
