### ISSUE TITLE
Lsp keep reload the project

### ISSUE THREAD

**Issue by Wordluc** [razzmatazz/csharp-language-server#165]
with this opt
`local cap = vim.tbl_deep_extend("force",
	vim.lsp.protocol.make_client_capabilities(),
	require('cmp_nvim_lsp').default_capabilities()
)
cap.workspace.didChangeWatchedFiles.dynamicRegistration = true`

Lsp reload all the project(saying that is changed .sln) even thought i had not changed anything.

![image](https://github.com/razzmatazz/csharp-language-server/assets/40872910/6eb67840-a8e7-4d37-8d6b-e0094cd981f3)

ps:i use didChangeWatchedFiles to notify the server when i delete a file

**Comment by Wordluc** [comment]
it seems that lsp don't support file operation for this i use "didChangeWatchedFiles"

**Comment by razzmatazz** [comment]
Hey @Wordluc which OS is this?

**Comment by Wordluc** [comment]
Windows 10

**Comment by Wordluc** [comment]
for now i found this solutions:
`
local cap = require('lspconfig').util.default_config.capabilities
cap.workspace.didChangeWatchedFiles.dynamicRegistration = true
local oldMath = require("vim.lsp._watchfiles")._match

require("vim.lsp._watchfiles")._match = function(a, b)
	if string.find(b, '.csproj') or string.find(b, '.sln') then
		return false
	end

	return oldMath(a, b)
end

`

**Comment by tcx4c70** [comment]
Hi @Wordluc , `change to .csproj detected, will reload solution` means [the client tells the server that some `csproj` files are changed](https://github.com/razzmatazz/csharp-language-server/blob/master/src/CSharpLanguageServer/Handlers/Workspace.fs#L87-L93). Could you please share the trace log of which files are in the `workspace/didChangeWatchedFiles`? I guess there are some `csproj` files are in it.

From the workaround you shared, I think the client you are using sends unchanged files in `workspace/didChangeWatchedFiles`.

And from [lsp spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWatchedFiles), it's better to watch file changes in client side and client should send the changed files to server.

**Comment by Wordluc** [comment]
@tcx4c70 without the workaround are present diffent .csproj, the thing is that i don't change them, so like you said it's a problem of the client so nvim lsp?
or is there something that "change" or "save" some csproj?

**Comment by Wordluc** [comment]
the problem is that i use visual studio to build and debug the solution since visual studio open .sln to load the solution
