### ISSUE TITLE
csharp-ls cannot jump to metadata 

### ISSUE THREAD

**Issue by serezlan** [razzmatazz/csharp-language-server#2]
Hi,

I've tested v0.1.5 of csharp-ls and still unable to jump to metadata.

Steps to reproduce:

- Create new hello world project
- - On Console or WriteLine, do lsp-find-definition 
- 
Expected Result:

- Jump to intended definition 
- 
Actual Behavior:

- Still on the same buffer
- 
System:

- Emacs 27.2
- - Debian 10
- - lsp latest
- csharp-ls, 0.1.5.0
- 
[log.txt](https://github.com/razzmatazz/csharp-language-server/files/7470869/log.txt)
[log-csharp.txt](https://github.com/razzmatazz/csharp-language-server/files/7470871/log-csharp.txt)

**Comment by razzmatazz** [comment]
lsp-csharp.txt contains this:
```
 "message": "csharp-ls: msbuildWorkspace.Diagnostics: [Failure] Msbuild failed when processing the file '/home/serezlan/Workspace/csharp/training/SasanaLinkedList/SasanaLinkedList.csproj' with message: /usr/share/dotnet/sdk/5.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets: (241, 5): The \"ResolvePackageAssets\" task failed unexpectedly.\nNuGet.Packaging.Core.PackagingException: Unable to find fallback package folder '/usr/share/dotnet/sdk/NuGetFallbackFolder'.\n   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)\n   at Microsoft.NET.Build.Tasks.NuGetPackageResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)\n   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders)\n   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(LockFile lockFile)\n   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)\n   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)\n   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)\n   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()\n   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()\n   at Microsoft.NET.Build.Tasks.TaskBase.Execute()\n   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\n   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)",
  "type": 4
```

some googling points me to:
- https://stackoverflow.com/questions/52113847/docker-build-complains-it-cant-find-nuget-fallback-package-folder
- https://youtrack.jetbrains.com/issue/RIDER-34671
- https://www.krank.se/2020/09/29/weird-vscodeomnisharp-nuget-error-solved/

could you try to deleting bin+obj folders and then run `dotnet build` again on the directory?

are you using mono/older version of dotnet on the same project or maybe jetbrains rider?

**Comment by serezlan** [comment]
OK @razzmatazz  
I got it to work on fresh dotnet core project.

The training folder was an old repo back when lsp was not a thing. 

Thanks.
