### ISSUE TITLE
decompile for Mircrosoft.ML

### ISSUE THREAD

**Issue by chen244** [razzmatazz/csharp-language-server#22]
csharp_ls: -32000: Failed to resolve assembly: 'Microsoft.ML.DataView, Version=1.0.0.0, Culture=neutral, PublicKeyToken
=cc7b13ffcd2ddd51'

Is it a bug?

**Comment by chen244** [comment]
> 

I use dotnet6 and try to decompile the Microsoft.Ml . When I want to check the 
"context.Data.LoadFromTextFile", neovim get nil from csharp_ls. decompile cannot work.

**Comment by chen244** [comment]
> didn't see this before myself
> 
>     * does it still work for other types, like those in System.Runtime?
> 
>     * what kind of framework/.net core version are you running
> 
>     * what is your platform?


I use dotnet6 and try to decompile the Microsoft.Ml . When I want to check the 
"context.Data.LoadFromTextFile", neovim get nil from csharp_ls. decompile cannot work. But other code can work very will, like godot or code in System.Runtime

**Comment by razzmatazz** [comment]
also if you have a minimal test case that I could try to replicate myself that would be helpful

most probably the issue is how I configure ICSharpCode.Decompiler with assembly paths

**Comment by chen244** [comment]
> also if you have a minimal test case that I could try to replicate myself that would be helpful
> 
> most probably the issue is how I configure ICSharpCode.Decompiler with assembly resolution paths

https://github.com/chen244/MLTrainer/blob/master/Trainer.cs#L15

Jump this line

**Comment by razzmatazz** [comment]
I have *just* released a new version of csharp-ls where among other things i have upgraded icsharpcode.decompiler

could you check -- *maybe, just maybe* it has fixed your issue?

**Comment by chen244** [comment]
> I have _just_ released a new version of csharp-ls where among other things i have upgraded icsharpcode.decompiler
> 
> could you check -- _maybe, just maybe_ it has fixed your issue?
> 
> https://www.nuget.org/packages/csharp-ls/0.4.0

Ha, it still not works. But it is ok, most codes can be easily decompile

**Comment by razzmatazz** [comment]
@chen244 I *think* I have fixed this issue with https://github.com/razzmatazz/csharp-language-server/commit/1633f5801278384e47c19ee36b9d5f7ab27ad350 -- at least NHibernate opens for me now, so I suspect it is the same issue

will release a new version soon

**Comment by chen244** [comment]
> @chen244 I *think* I have fixed this issue with https://github.com/razzmatazz/csharp-language-server/commit/1633f5801278384e47c19ee36b9d5f7ab27ad350 -- at least NHibernate opens for me now, so I suspect it is the same issue
> 
> will release a new version soon

Greate！

**Comment by razzmatazz** [comment]
please reopen the issue if things still don't work after upgrade

**Comment by chen244** [comment]
> please reopen the issue if things still don't work after upgrade

Solved,Thanks
