### ISSUE TITLE
handleInitialize tries to register capabilities prematurely

### ISSUE THREAD

**Issue by vytautassurvila** [razzmatazz/csharp-language-server#26]
When csharp-language-server is used with vscode-languageclient then client crashes with error `Unhandled method client/registerCapability`. If I read code right culprit is in following two lines https://github.com/razzmatazz/csharp-language-server/blob/520ef3588ba45c8ec95b7f01969c5dfa33dc1d75/src/CSharpLanguageServer/Server.fs#L583-L584 Those do send `client/registerCapability` to client immediately before emitting initialize result.

According to Lsp `initialize` request
> In addition the server is not allowed to send any requests or notifications to the client until it has responded with an [InitializeResult](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeResult), with the exception that during the initialize request the server is allowed to send the notifications window/showMessage, window/logMessage and [telemetry/event](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#telemetry_event) as well as the window/showMessageRequest request to the client

https://microsoft.github.io/language-server-protocol/specification#initialize

In order to register dynamic capabilities `initialized` notification should be used instead:
> The server can use the initialized notification for example to dynamically register capabilities

https://microsoft.github.io/language-server-protocol/specification#initialized

And the vscode-languageclient code that starts listening on client/registerCapability only after successful initialization (first and last lines are relevant) https://github.com/microsoft/vscode-languageserver-node/blob/d9eeaf626fd9362eec69fe63322d15760f6794d1/client/src/common/client.ts#L3402-L3430

**Comment by razzmatazz** [comment]
should be fixed with https://github.com/razzmatazz/csharp-language-server/commit/333f9f4198d6aa422aedfda0e433c2cd930714dc

releasing 0.4.2 in a moment..

**Comment by vytautassurvila** [comment]
Thanks, vscode-languageclient does not crash anymore with 0.4.2
