### ISSUE TITLE
support for dotnet 6.0.100?

### ISSUE THREAD

**Issue by Tus1688** [razzmatazz/csharp-language-server#3]
Hi, first of all thank you for your amazing work! I am really loving it! Today, I upgrade dotnet to 6.0.100, unfortunately I didn't find csharp_ls server working as it supposed to be, in contrast it working like a charm before dotnet upgrade.

I haven't been able to find a workaround except downgrading dotnet. Do you have any clues?
client: 

- Neovim nightly
- neovim-lsp: latest
- csharp-ls: 0.1.5.0

```
[START][2021-11-09 09:54:51] LSP logging initiated
[ERROR][2021-11-09 09:54:52] .../vim/lsp/rpc.lua:412    "rpc"   "csharp-ls"     "stderr"        "It was not possible to find any compatible framework version\nThe framework 'Microsoft.NETCore.App', version '5.0.0' (arm64) was not found.\n  - The following frameworks were found:\n      6.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]\n\nYou can resolve the problem by installing the specified framework and/or SDK.\n\nThe specified framework can be found at:\n  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=arm64&rid=osx.11.1-arm64\n"
[ERROR][2021-11-09 09:55:05] .../vim/lsp/rpc.lua:412    "rpc"   "csharp-ls"     "stderr"        "It was not possible to find any compatible framework version\nThe framework 'Microsoft.NETCore.App', version '5.0.0' (arm64) was not found.\n  - The following frameworks were found:\n      6.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]\n\nYou can resolve the problem by installing the specified framework and/or SDK.\n\nThe specified framework can be found at:\n  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=arm64&rid=osx.11.1-arm64\n"
[START][2021-11-09 09:55:52] LSP logging initiated
[ERROR][2021-11-09 09:55:53] .../vim/lsp/rpc.lua:412    "rpc"   "csharp-ls"     "stderr"        "It was not possible to find any compatible framework version\nThe framework 'Microsoft.NETCore.App', version '5.0.0' (arm64) was not found.\n  - The following frameworks were found:\n      6.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]\n\nYou can resolve the problem by installing the specified framework and/or SDK.\n\nThe specified framework can be found at:\n  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=arm64&rid=osx.11.1-arm64\n"
[START][2021-11-09 09:57:26] LSP logging initiated
```

**Comment by razzmatazz** [comment]
Hey @Tus1688 

Thanks for your kind words! I need to upgrade Roslyn and msbuild libs to support c# 10 and net6 features. Hopefully will do that today or tommorow.

but I your case I think you can try to install .net 5 in parallel to .net 6. with “dotnet-install.sh” (you can google it; you will need to setup DOTNET_PATH and PATH to point to ~/.dotnet). Although in your case it seems you are on M1 Mac where .net 5 is not native but .net 6 is, so I dunno if it will work like this, but you can try :)

otherwise you could downgrade and wait for my next release on .net6

**Comment by Tus1688** [comment]
Thank you for replying @razzmatazz, can't wait receiving update for it 👍

**Comment by razzmatazz** [comment]
Reopening as @josteink has reported the same in https://github.com/emacs-lsp/lsp-mode/issues/3198

FYI @josteink

**Comment by razzmatazz** [comment]
OK, I have released 0.1.6 with support for net6.0 projects (plus some other improvements)

https://www.nuget.org/packages/csharp-ls/0.1.6 (takes some time to appear on nuget page/search results due to indexing and validation that is performed)

@Tus1688 close if things work for you (once you get it updated)

**Comment by razzmatazz** [comment]
OK, published
```
dotnet tool install -g csharp-ls                                                                                                                                                              
You can invoke the tool using the following command: csharp-ls                                                                                                                                
Tool 'csharp-ls' (version '0.1.6') was successfully installed.                                                                                                                                
```

**Comment by josteink** [comment]
That was fast! Thanks for the fix! 👍

**Comment by Tus1688** [comment]
Thanks for the fix @razzmatazz ! It is fully working in neovim  👍
