### ISSUE TITLE
The behavior of cshap_ls on neovim 0.7 is abnormal 

### ISSUE THREAD

**Issue by Decodetalkers** [razzmatazz/csharp-language-server#31]
I think I would better also mention this here. I am confused.. Before 0.7 it works well. I cannot figure out how it comes.
https://github.com/neovim/neovim/issues/18147

**Comment by razzmatazz** [comment]
I am still on a vacation for a while (until next week) -- will take a look then

**Comment by chen244** [comment]
Hello ,any update?

**Comment by razzmatazz** [comment]
Sorry, busy with other things. I don't have nvim setup myself yet.

**Comment by razzmatazz** [comment]
ok, I wrote the same thing to neovim/neovim#18147 but here it follows:

---

Hmm, I believe csharp-ls has broken behaviour wr.t. incremental sync..

I was trying to replicate the problem and managed to setup packer+nvim-lspconfig and immediately hit the problem where typing things too fast in nvim triggers document sync problems.

My plan here is to:
- [ ] update csharp-ls to properly handle full sync behaviour from the client (via negotation)
- [ ] add a command line param to force full sync
- [ ] add a PR to nvim-lspconfig to set this param until we have this partial sync bug diagnosed (whether this is csharp-ls or nvim at fault)
- [ ] fix the actual problem

**Comment by razzmatazz** [comment]
Hey @Decodetalkers sorry for taking this long.

I think I have fixed the bug -- it was actually a problem with how csharp-ls was handling incremental file changes. At least for me typing fast in nvim does not cause sync errors, so hopefully your problem with formatting is fixed too. Please confirm if so.

I have release a new version of csharp-ls:
- https://www.nuget.org/packages/csharp-ls/0.5.1

**Comment by Decodetalkers** [comment]
> Hey @Decodetalkers sorry for taking this long.
> 
> I think I have fixed the bug with 396387cead17de963197f0f5af5a0d89860ec6f3 -- it was actually a problem with how csharp-ls was handling incremental file changes. At least for me typing fast in nvim does not cause sync errors anymore, so hopefully your problem with formatting is fixed too. Please confirm if so.
> 
> I have released a new version of csharp-ls:
> - https://www.nuget.org/packages/csharp-ls/0.5.1
> 
> 

Yes, fixed

**Comment by razzmatazz** [comment]
Closing this then
