### ISSUE TITLE
Unused namespace should use warning

### ISSUE THREAD

**Issue by Decodetalkers** [razzmatazz/csharp-language-server#35]
I noticed that you use error to show the namespace be usinged but not used.

I think it should use warning to show that message

![image](https://user-images.githubusercontent.com/60290287/169455977-f7bc71f2-ccaa-4745-8c97-a95889dc13c0.png)

**Comment by razzmatazz** [comment]
Should be fixed with https://github.com/razzmatazz/csharp-language-server/commit/989d0ed682e96dd291cc6401b4f4bb317637ba7f -- will be released w/the next version
