### ISSUE TITLE
csharp-ls seems to conflate definition with implementation?

### ISSUE THREAD

**Issue by josteink** [razzmatazz/csharp-language-server#4]
Not sure if this is the fault of `csharp-ls` or not, but it seems like a good place to start :smile: 

Consider the following c# code:

````c#
interface IDemo
{
    void Foo();
}

class Demo : IDemo
{
    void Foo()
    {
        Console.WriteLine("Bar");
    }
}
````

When positioning the cursor at `IDemo` (line 6) and selecting (in Emacs) `lsp-find-definition` I'm taken to line 1, where the interface is defined. This makes sense.

However when I use `lsp-find-implementation` at `IDemo` (line 1), I expect to be given the implementations of that interface (line 6). Instead the behaviour seems to be just like `lsp-find-definition`, and I remain at line 1.

Are these two functions implemented the same way inside `csharp-ls`? Or is this a `lsp-mode` issue? Or have I simply misunderstood something about what the current C# LSP providers are capable of?

**Comment by josteink** [comment]
Looking at the code that does indeed seem to be the case:

https://github.com/razzmatazz/csharp-language-server/blob/242409a7e15af3d53312a5416dfa4584be8d635a/src/CSharpLanguageServer/Server.fs#L685-L686

**Comment by razzmatazz** [comment]
Yeah, that was a cheap shot on my part to get something working but I didn’t get that much into semantic differences to realize it’s a bad idea :)

**Comment by josteink** [comment]
Fair enough. But IMO it's probably better/more correct to *not* advertise the "find implementation" capability until that is sorted out.

What do you think?

**Comment by razzmatazz** [comment]
oh definitely
