### ISSUE TITLE
lsp-mode loading spinner no longer working

### ISSUE THREAD

**Issue by joefbsjr** [razzmatazz/csharp-language-server#40]
I was using version 0.3.x and when loading a new project, lsp-mode was able to show that the project/solution was loading. Now in version 0.5.3 lsp-mode gives no indication of loading, it thinks the project loaded instantly, which is not true. So I have to wait and arbitrarily try to use commands until something works showing that the solution was actually loaded.

**Comment by razzmatazz** [comment]
I believe this broke with https://github.com/razzmatazz/csharp-language-server/issues/26

previously we didn't respond to client's `initialize` request before loading a solution, but after #26 we're start loading solution after the client sends us `initialized` notification, changed with https://github.com/razzmatazz/csharp-language-server/commit/333f9f4198d6aa422aedfda0e433c2cd930714dc

will take a look..

**Comment by razzmatazz** [comment]
@joefbsjr I think I fixed this with c29fe97 -- will release a new version somewhat later

**Comment by razzmatazz** [comment]
https://www.nuget.org/packages/csharp-ls/0.5.4 has been released that should fix the issue
