### ISSUE TITLE
Wrong kind of workspace/symbol in lsp-mode for classes/structs

### ISSUE THREAD

**Issue by joefbsjr** [razzmatazz/csharp-language-server#41]
When requesting "workspace/symbol", lsp-mode receives `Classes` and `Structs` as `File`. I don't know if this happens with other kinds, as well. Methods, Properties and Fields seems to be working as intended.

**Comment by razzmatazz** [comment]
fixed with https://github.com/razzmatazz/csharp-language-server/commit/328dd2abbb9911a4494e0b581aafb5b600e97186 will release a new version later

**Comment by razzmatazz** [comment]
https://www.nuget.org/packages/csharp-ls/0.5.4 has been released that should fix the issue
