### ISSUE TITLE
How to set indentation to 2 spaces?

### ISSUE THREAD

**Issue by blldw** [razzmatazz/csharp-language-server#48]
I am accustomed to using 2 spaces of indentation, and I would like to know whether there is a variable to keep the indentation to 2 spaces or if there is any way to keep these 2 spaces of indentation. When I input a `;', the code becomes 4 spaces of indentation automatically, and I want to avoid this happening.

**Comment by razzmatazz** [comment]
Hey @blldw; which editor are you using? Asking to make sure it is lsp formatting features that are formatting your code and not the editor.

At the moment csharp-ls provides about 0 :) configuration -- but this should be feasible to do by setting roslyn configurables.

**Comment by razzmatazz** [comment]
hmm, have you tried configuring `c-basic-offset`, `tab-width` and `evil-shift-width` (if you're using evil?)

I am not 100% sure how it is setup on your machine, but I think by default `csharp-mode` does indentation unless you have specific configuration

e.g. I have this on my config.el file which works quite nicely for my coding style..
```
(after! csharp-mode
  (defun sm-csharp-mode-setup ()
    (setq indent-tabs-mode nil)
    (setq c-syntactic-indentation t)
    (c-set-style "ellemtel")
    (setq c-basic-offset 4)
    (setq truncate-lines t)
    (setq tab-width 4)
    (setq evil-shift-width 4))
```

also @kstatz12 is working on .editorconfig support so maybe that will help https://github.com/razzmatazz/csharp-language-server/issues/49

in your case maybe you don't even need changes in csharp-ls if you set proper values in .editorconfig and you have https://github.com/editorconfig/editorconfig-emacs plugged in..

**Comment by blldw** [comment]
If I only use csharp-mode when writing csharp code, 2 space indentation works fine; However, If I enable lsp-mode, the problem I posted will occur:
```
(use-package csharp-mode
  :hook (csharp-mode . lsp))
```

@razzmatazz Your configuration for 4 spaces indentation worked, but not the solution for 2 space indentation.
