### ISSUE TITLE
README contains misleading information wrt to compatibility

### ISSUE THREAD

**Issue by josteink** [razzmatazz/csharp-language-server#5]
The README clearly states:

> `csharp-ls` unapologetically requires .NET 6 SDK to work and (probably) does not support .NET 3/4.x projects (.NET Framework)

Just wanted to let you know that I've now tested the latest `csharp-ls` and it works *just fine* with projects in other .NET Core versions (3.x, 5.0).

I even tried it on some regular .NET Framework projects (.net 4.8) with SDK-format CSPROJ-files, and that worked fine too.

So yeah... Now you know. Feel free to update the README based on that info... Or don't :smile:

**Comment by razzmatazz** [comment]
This is great! I didn’t test it with framework projects, but I suspected it should work with older csproj

**Comment by josteink** [comment]
It might be Roslyn which is just amazing or it might just be because I have all those SDKs (and mono 6.12) installed. 

Either way I thought it might be worth reporting 🙂
