### ISSUE TITLE
Formatting changes tabs to spaces and does not respect vim settings passed by coc.nvim

### ISSUE THREAD

**Issue by fl0kng** [razzmatazz/csharp-language-server#58]
Hi,

I am using csharp-ls with coc.nvim. My indentation settings are:

`	shiftwidth = 4,                         
	tabstop = 4,                             
	expandtab = false,
`

Passed on by coc.nvim as the following... looks fine to me.

`[Trace - 1:36:19 PM] Sending request 'textDocument/formatting - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fl0kng/dev/Test.cs"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": false,
        "insertFinalNewline": true
    }
}`#

Does csharp-ls handle formatting options? I had a quick look, and it seems as if it does not do anything... ;)
Thanks in advance and kind regards,
Florian

**Comment by razzmatazz** [comment]
Hi @fl0kng 

At this point csharp-ls uses the defaults from roslyn. What we need to do is to support `.editorconfig` from my POV. Related issue is:
- https://github.com/razzmatazz/csharp-language-server/issues/49

**Comment by fl0kng** [comment]
Not sure what you mean by that, but I would have assumed that the parameters in the actual request to the lsp (see above) get processed / handed down the line... but any fix is greatly appreciated ;)

**Comment by razzmatazz** [comment]
I just merged @weirongxu's PR related to this issue, but I am not using vim/coc so I cannot verify the fix.
