### ISSUE TITLE
[question] Why it prints so many information when used in coc.nvim when I opend a cs file.

### ISSUE THREAD

**Issue by SetsuikiHyoryu** [razzmatazz/csharp-language-server#64]
When I opend a cs file, it prints so many information and need I press key to display them.  
Is it meens some problem happend? If not, it's so inconvenient:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/57035251/216221021-58fd02c8-7480-4d7f-8ffe-e8f16c94b7b3.png">

This is the config in my coc config file:

```json
{
  "languageserver": {
    "csharp-ls": {
      "command": "csharp-ls",
      "filetypes": ["cs"],
      "rootPatterns": ["*.csproj", ".vim/", ".git/", ".hg/"]
    }
  }
}
```

**Comment by razzmatazz** [comment]
Hey @SetsuikiHyoryu 

I understand these messages can be obnoxious -- will try to tune them down a bit. Those get hidden properly on emacs, but coc.nvim probably shows them in a more pronounced way.

> Is it meens some problem happend
No, these, are just diagnostics messages and does not inform about an error/issue of any sort.

**Comment by SetsuikiHyoryu** [comment]
@razzmatazz 

Thankyou for your answer, I understand.
