### ISSUE TITLE
Release request: 0.7.1

### ISSUE THREAD

**Issue by sharpSteff** [razzmatazz/csharp-language-server#79]
it would be great if you can release a 0.7.1 with the fix from #76

**Comment by razzmatazz** [comment]
will do, some time later this week, can you use locally-built version in the meantime?

**Comment by sharpSteff** [comment]
that's all I need to here

**Comment by razzmatazz** [comment]
a new version has just been released with your fix:
- https://www.nuget.org/packages/csharp-ls/0.7.1 (still indexing, but should be available in 10 or so minutes)

**Comment by razzmatazz** [comment]
And thanks for your contribution, I really appreciate all the investigation work you did.

**Comment by sharpSteff** [comment]
@razzmatazz thanks for the quick release. I'm going to switch the lsp backend of my lapce c# plugin [https://github.com/sharpSteff/lapce-csharp-plugin](C# for Lapce) to your csharp lsp with v2.0.0. it works so good 👍
