### ISSUE TITLE
Order of suggestions of code-fixes is not really optimized, especially with imports

### ISSUE THREAD

**Issue by josteink** [razzmatazz/csharp-language-server#9]
Consider the following code:

**a/Class1.cs**
````c#
namespace A
{
    public class Class1
    {
        // code
    }
}
````

**b/Class2.cs**
````c#
namespace B
{
    public class Class2
    {
        var instance = new Class1();
    }
}
````

Then put your cursor on `Class1()` and invoke `M-x lsp-execute-code-action` in Emacs, or similar action in other editor.

**Observed that**

You will be provided several different options:

![image](https://user-images.githubusercontent.com/411338/141305636-c7b30e17-57b4-471e-bc24-e3382f3bd0f9.png)
(Screenshot for demonstrationg-purposes. Does not match example code 1-to-1)

**Expected that**

Generally, in my experience, some actions are almost always "more" preferred than others.

In this particular case I almost always want to have `using`-statements as first suggestion, explicit-namespacing as second and create new class as third and expect to find code-fixes in that order.

Does the LSP protocol provide any sort of ... priority for the code actions or is it up to the LSP-client itself to determine how to present them?

**Comment by razzmatazz** [comment]
It looks like there is :) I thought there wasnt.

‘CodeAction.isPreferred’
https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#codeAction

**Comment by josteink** [comment]
On the same spec there’s also CodeActionKind:

    kind?: CodeActionKind;

It seems one possible value for that is `quickfix`. 

So I guess we should prioritise isPreferred and quickfix actions, and in that order?

**Comment by razzmatazz** [comment]
pending on https://github.com/ionide/LanguageServerProtocol/pull/4/files

**Comment by razzmatazz** [comment]
> pending on [ionide/LanguageServerProtocol#4](https://github.com/ionide/LanguageServerProtocol/pull/4)

ok, that one has been merged

**Comment by josteink** [comment]
Tested and works. Great stuff! :smiley:

**Comment by josteink** [comment]
This works 100% as I described in the "expected" section in the issue, so I guess I have no choice but consider this 100% resolved :smile:
