### ISSUE TITLE
Neovim color scheme changes when file is reloaded

### ISSUE THREAD

**Issue by weskoerber** [razzmatazz/csharp-language-server#92]
When I open a `.cs` file (after opening neovim but before the csharp-ls attaches to the buffer) the colorscheme is gruvbox, as expected. However, if I reload the file or write to it after csharp-ls attaches to the buffer, the colorscheme changes. It doesn't change drastically, just some token colors are changed. This wasn't happening with omnisharp before I switched, so that's why I believe it's being caused by csharp-ls.

**Before csharp-ls attaches to buffer**
![image](https://user-images.githubusercontent.com/28966224/236580389-078e9ac8-0cce-49a3-b1c1-68d168b134c0.png)

**After csharp-ls attaches to buffer**
![image](https://user-images.githubusercontent.com/28966224/236580409-c6ec00c6-f3d1-472f-952e-3af872da58a1.png)

**Comment by razzmatazz** [comment]
hi @weskoerber 

csharp-ls now implements support for LSP semantic token support (thanks to @tcx4c70) where LSP server is sending details about tokens on your file and their type to the editor -- the editor then uses this information to provide additional features based on this semantic information about the file

you may want to check documentation in neovim how to disable syntax coloring based on lsp semantic tokens

"its a feature, not a bug" :)

**Comment by weskoerber** [comment]
> "its a feature, not a bug" :)

I figured my ignorance to both neovim and csharp-ls would show. 

Thanks for the info, it led me straight to an easy fix.
